declare module 'react-reveal'
declare module 'react-reveal/Fade'
declare module 'react-reveal/Flip'
declare module 'react-reveal/Slide'
declare module 'react-reveal/Zoom'
declare module 'react-reveal/Bounce'